version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: pnpm
    directory: /
    schedule:
      interval: weekly
    groups:
      pnpm-development:
        dependency-type: development
        update-types:
          - minor
          - patch
      pnpm-production:
        dependency-type: production
        update-types:
          - patch
