name: Develop Self Versioning

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

permissions:
  contents: write

jobs:
  develop-version:
    if: github.event.pull_request.merged == true
    name: Develop Self Versioning job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout step
        id: checkout
        uses: actions/checkout@v4

      - name: New Version step
        id: new-version
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prefix: 'v'
          postfix: 'dev'
